// This file has been generated by Py++.

#include "stdafx.h"
#include "pypluspluscommon.h"
#include "boost/python.hpp"
#include "__call_policies.pypp.hpp"
#include "filesystem.h"
#include "filesystemsingleton.pypp.hpp"

namespace bp = boost::python;

struct StaticSingleton_less__osiris_scope_FileSystem_comma__true__greater__wrapper : ::osiris::StaticSingleton< osiris::FileSystem, true >, ::osiris::PythonWrapper< ::osiris::StaticSingleton< osiris::FileSystem, true > > {

    StaticSingleton_less__osiris_scope_FileSystem_comma__true__greater__wrapper( )
    : ::osiris::StaticSingleton<osiris::FileSystem, true>( )
      , ::osiris::PythonWrapper< ::osiris::StaticSingleton< osiris::FileSystem, true > >(){
        // nullptr constructor
    
    }

    static boost::python::object instance(  ){
        ::osiris::PythonThreadSaver __pythreadSaver;
        ::osiris::FileSystem * result = ::osiris::StaticSingleton<osiris::FileSystem, true>::instance();
        __pythreadSaver.restore();
        typedef bp::return_value_policy< bp::reference_existing_object > call_policies_t;
        return boost::python::object( pyplusplus::call_policies::make_object< call_policies_t, ::osiris::FileSystem * >( result ) );
    }

};

void register_FileSystemSingleton_class(){

    ::boost::python::class_< StaticSingleton_less__osiris_scope_FileSystem_comma__true__greater__wrapper, ::boost::noncopyable >( "FileSystemSingleton", ::boost::python::no_init )    
        .def( ::boost::python::init< >() )    
        .def( 
            "instance"
            , (boost::python::object (*)(  ))( &StaticSingleton_less__osiris_scope_FileSystem_comma__true__greater__wrapper::instance ) )    
        .staticmethod( "instance" );

}
