// This file has been generated by Py++.

#include "stdafx.h"
#include "pypluspluscommon.h"
#include "boost/python.hpp"
#include "__call_policies.pypp.hpp"
#include "htmltablecell.h"
#include "datatree.h"
#include "htmlattributes.h"
#include "htmlevent.h"
#include "eventssource.h"
#include "htmlvirtualpage.h"
#include "htmlwriter.h"
#include "httprequest.h"
#include "httpresponse.h"
#include "httpsession.h"
#include "htmltableheader.h"
#include "htmltablecell.pypp.hpp"

namespace bp = boost::python;

struct HtmlTableCell_wrapper : ::osiris::HtmlTableCell, ::osiris::PythonWrapper< ::osiris::HtmlTableCell > {

    HtmlTableCell_wrapper( )
    : ::osiris::HtmlTableCell( )
      , ::osiris::PythonWrapper< ::osiris::HtmlTableCell >(){
        // null constructor
    
    }

    static boost::python::object getColSpan( ::osiris::HtmlTableCell const & inst ){
        ::osiris::PythonThreadSaver __pythreadSaver;
        ::osiris::HtmlUnit result = inst.getColSpan();
        __pythreadSaver.restore();
        return boost::python::object( result );
    }

    static boost::python::object getRowSpan( ::osiris::HtmlTableCell const & inst ){
        ::osiris::PythonThreadSaver __pythreadSaver;
        ::osiris::HtmlUnit result = inst.getRowSpan();
        __pythreadSaver.restore();
        return boost::python::object( result );
    }

    virtual void onRender( ::osiris::HtmlWriter & writer ){
        ::osiris::PythonState __pystate(getPythonThreadState());
        if( ::osiris::PythonOverride func_onRender = this->get_override( "onRender" ) )
            func_onRender( boost::ref(writer) );
        else{
            __pystate.leave();
            this->::osiris::HtmlTableCell::onRender( boost::ref(writer) );
        }
    }
    
    virtual void default_onRender( ::osiris::HtmlWriter & writer ){
        ::osiris::PythonThreadSaver __pythreadSaver;
        ::osiris::HtmlTableCell::onRender( boost::ref(writer) );
    }

    static void setColSpan( ::osiris::HtmlTableCell & inst, ::osiris::HtmlUnit const & value ){
        ::osiris::PythonThreadSaver __pythreadSaver;
        inst.setColSpan(value);
        __pythreadSaver.restore();
    }

    static void setRowSpan( ::osiris::HtmlTableCell & inst, ::osiris::HtmlUnit const & value ){
        ::osiris::PythonThreadSaver __pythreadSaver;
        inst.setRowSpan(value);
        __pythreadSaver.restore();
    }

    bool decodeEvent( ::osiris::String const & command, ::osiris::String & eventName, ::osiris::HtmlEvent & e ) const {
        return ::osiris::IHtmlControl::decodeEvent( boost::ref(command), boost::ref(eventName), boost::ref(e) );
    }

    ::osiris::String encodeEvent( ::osiris::String const & eventName, ::osiris::HtmlEvent const * e=(nullptr) ) const {
        return ::osiris::IHtmlControl::encodeEvent( boost::ref(eventName), boost::python::ptr(e) );
    }

    virtual ::boost::shared_ptr< osiris::HttpSession > getSession(  ) const  {
        ::osiris::PythonState __pystate(getPythonThreadState());
        if( ::osiris::PythonOverride func_getSession = this->get_override( "getSession" ) )
            return func_getSession(  );
        else{
            __pystate.leave();
            return this->::osiris::IHtmlControl::getSession(  );
        }
    }
    
    ::boost::shared_ptr< osiris::HttpSession > default_getSession(  ) const  {
        ::osiris::PythonThreadSaver __pythreadSaver;
        return ::osiris::IHtmlControl::getSession( );
    }

    virtual void onEvent( ::osiris::String const & name, ::osiris::IEvent * e=(nullptr) ){
        ::osiris::PythonState __pystate(getPythonThreadState());
        if( ::osiris::PythonOverride func_onEvent = this->get_override( "onEvent" ) )
            func_onEvent( boost::ref(name), boost::python::ptr(e) );
        else{
            __pystate.leave();
            this->::osiris::IHtmlControl::onEvent( boost::ref(name), boost::python::ptr(e) );
        }
    }
    
    virtual void default_onEvent( ::osiris::String const & name, ::osiris::IEvent * e=(nullptr) ){
        ::osiris::PythonThreadSaver __pythreadSaver;
        ::osiris::IHtmlControl::onEvent( boost::ref(name), boost::python::ptr(e) );
    }

    virtual void onInit(  ){
        ::osiris::PythonState __pystate(getPythonThreadState());
        if( ::osiris::PythonOverride func_onInit = this->get_override( "onInit" ) )
            func_onInit(  );
        else{
            __pystate.leave();
            this->::osiris::IHtmlControl::onInit(  );
        }
    }
    
    virtual void default_onInit(  ){
        ::osiris::PythonThreadSaver __pythreadSaver;
        ::osiris::IHtmlControl::onInit( );
    }

    virtual void onLoad(  ){
        ::osiris::PythonState __pystate(getPythonThreadState());
        if( ::osiris::PythonOverride func_onLoad = this->get_override( "onLoad" ) )
            func_onLoad(  );
        else{
            __pystate.leave();
            this->::osiris::IHtmlControl::onLoad(  );
        }
    }
    
    virtual void default_onLoad(  ){
        ::osiris::PythonThreadSaver __pythreadSaver;
        ::osiris::IHtmlControl::onLoad( );
    }

    virtual void onLoadViewState( ::osiris::DataTree const & state ){
        ::osiris::PythonState __pystate(getPythonThreadState());
        if( ::osiris::PythonOverride func_onLoadViewState = this->get_override( "onLoadViewState" ) )
            func_onLoadViewState( boost::ref(state) );
        else{
            __pystate.leave();
            this->::osiris::IHtmlControl::onLoadViewState( boost::ref(state) );
        }
    }
    
    virtual void default_onLoadViewState( ::osiris::DataTree const & state ){
        ::osiris::PythonThreadSaver __pythreadSaver;
        ::osiris::IHtmlControl::onLoadViewState( boost::ref(state) );
    }

    virtual void onPreRender(  ){
        ::osiris::PythonState __pystate(getPythonThreadState());
        if( ::osiris::PythonOverride func_onPreRender = this->get_override( "onPreRender" ) )
            func_onPreRender(  );
        else{
            __pystate.leave();
            this->::osiris::IHtmlControl::onPreRender(  );
        }
    }
    
    virtual void default_onPreRender(  ){
        ::osiris::PythonThreadSaver __pythreadSaver;
        ::osiris::IHtmlControl::onPreRender( );
    }

    virtual void onSaveViewState( ::osiris::DataTree & state ){
        ::osiris::PythonState __pystate(getPythonThreadState());
        if( ::osiris::PythonOverride func_onSaveViewState = this->get_override( "onSaveViewState" ) )
            func_onSaveViewState( boost::ref(state) );
        else{
            __pystate.leave();
            this->::osiris::IHtmlControl::onSaveViewState( boost::ref(state) );
        }
    }
    
    virtual void default_onSaveViewState( ::osiris::DataTree & state ){
        ::osiris::PythonThreadSaver __pythreadSaver;
        ::osiris::IHtmlControl::onSaveViewState( boost::ref(state) );
    }

    virtual void renderAttributes( ::osiris::HtmlWriter & writer ) {
        ::osiris::PythonState __pystate(getPythonThreadState());
        if( ::osiris::PythonOverride func_renderAttributes = this->get_override( "renderAttributes" ) )
            func_renderAttributes( boost::ref(writer) );
        else{
            __pystate.leave();
            this->::osiris::IHtmlControl::renderAttributes( boost::ref(writer) );
        }
    }
    
    void default_renderAttributes( ::osiris::HtmlWriter & writer ) {
        ::osiris::PythonThreadSaver __pythreadSaver;
        ::osiris::IHtmlControl::renderAttributes( boost::ref(writer) );
    }

    virtual void renderChilds( ::osiris::HtmlWriter & writer ) {
        ::osiris::PythonState __pystate(getPythonThreadState());
        if( ::osiris::PythonOverride func_renderChilds = this->get_override( "renderChilds" ) )
            func_renderChilds( boost::ref(writer) );
        else{
            __pystate.leave();
            this->::osiris::IHtmlControl::renderChilds( boost::ref(writer) );
        }
    }
    
    void default_renderChilds( ::osiris::HtmlWriter & writer ) {
        ::osiris::PythonThreadSaver __pythreadSaver;
        ::osiris::IHtmlControl::renderChilds( boost::ref(writer) );
    }

    void saveViewState( ::osiris::DataTree & states ){
        ::osiris::IHtmlControl::saveViewState( boost::ref(states) );
    }

};

void register_HtmlTableCell_class(){

    { //::osiris::HtmlTableCell
        typedef ::boost::python::class_< HtmlTableCell_wrapper, ::boost::python::bases< ::osiris::IHtmlControl >, ::boost::noncopyable > HtmlTableCell_exposer_t;
        HtmlTableCell_exposer_t HtmlTableCell_exposer = HtmlTableCell_exposer_t( "HtmlTableCell", ::boost::python::init< >() );
        ::boost::python::scope HtmlTableCell_scope( HtmlTableCell_exposer );
        { //::osiris::HtmlTableCell::getColSpan
        
            typedef boost::python::object ( *getColSpan_function_type )( ::osiris::HtmlTableCell const & );
            
            HtmlTableCell_exposer.def( 
                "getColSpan"
                , getColSpan_function_type( &HtmlTableCell_wrapper::getColSpan ) );
        
        }
        { //::osiris::HtmlTableCell::getRowSpan
        
            typedef boost::python::object ( *getRowSpan_function_type )( ::osiris::HtmlTableCell const & );
            
            HtmlTableCell_exposer.def( 
                "getRowSpan"
                , getRowSpan_function_type( &HtmlTableCell_wrapper::getRowSpan ) );
        
        }
        { //::osiris::HtmlTableCell::onRender
        
            typedef void ( HtmlTableCell_wrapper::*onRender_function_type )( ::osiris::HtmlWriter & ) ;
            
            HtmlTableCell_exposer.def( 
                "onRender"
                , onRender_function_type( &HtmlTableCell_wrapper::default_onRender )
                , ( ::boost::python::arg("writer") ) );
        
        }
        { //::osiris::HtmlTableCell::setColSpan
        
            typedef void ( *setColSpan_function_type )( ::osiris::HtmlTableCell &,::osiris::HtmlUnit const & );
            
            HtmlTableCell_exposer.def( 
                "setColSpan"
                , setColSpan_function_type( &HtmlTableCell_wrapper::setColSpan )
                , ( ::boost::python::arg("inst"), ::boost::python::arg("value") ) );
        
        }
        { //::osiris::HtmlTableCell::setRowSpan
        
            typedef void ( *setRowSpan_function_type )( ::osiris::HtmlTableCell &,::osiris::HtmlUnit const & );
            
            HtmlTableCell_exposer.def( 
                "setRowSpan"
                , setRowSpan_function_type( &HtmlTableCell_wrapper::setRowSpan )
                , ( ::boost::python::arg("inst"), ::boost::python::arg("value") ) );
        
        }
        { //::osiris::IHtmlControl::decodeEvent
        
            typedef bool ( HtmlTableCell_wrapper::*decodeEvent_function_type )( ::osiris::String const &,::osiris::String &,::osiris::HtmlEvent & ) const;
            
            HtmlTableCell_exposer.def( 
                "decodeEvent"
                , decodeEvent_function_type( &HtmlTableCell_wrapper::decodeEvent )
                , ( ::boost::python::arg("command"), ::boost::python::arg("eventName"), ::boost::python::arg("e") ) );
        
        }
        { //::osiris::IHtmlControl::encodeEvent
        
            typedef ::osiris::String ( HtmlTableCell_wrapper::*encodeEvent_function_type )( ::osiris::String const &,::osiris::HtmlEvent const * ) const;
            
            HtmlTableCell_exposer.def( 
                "encodeEvent"
                , encodeEvent_function_type( &HtmlTableCell_wrapper::encodeEvent )
                , ( ::boost::python::arg("eventName"), ::boost::python::arg("e")=(nullptr) ) );
        
        }
        { //::osiris::IHtmlControl::getSession
        
            typedef ::boost::shared_ptr< osiris::HttpSession > ( ::osiris::IHtmlControl::*getSession_function_type )(  ) const;
            typedef ::boost::shared_ptr< osiris::HttpSession > ( HtmlTableCell_wrapper::*default_getSession_function_type )(  ) const;
            
            HtmlTableCell_exposer.def( 
                "getSession"
                , getSession_function_type(&::osiris::IHtmlControl::getSession)
                , default_getSession_function_type(&HtmlTableCell_wrapper::default_getSession) );
        
        }
        { //::osiris::IHtmlControl::onEvent
        
            typedef void ( HtmlTableCell_wrapper::*onEvent_function_type )( ::osiris::String const &,::osiris::IEvent * ) ;
            
            HtmlTableCell_exposer.def( 
                "onEvent"
                , onEvent_function_type( &HtmlTableCell_wrapper::default_onEvent )
                , ( ::boost::python::arg("name"), ::boost::python::arg("e")=(nullptr) ) );
        
        }
        { //::osiris::IHtmlControl::onInit
        
            typedef void ( HtmlTableCell_wrapper::*onInit_function_type )(  ) ;
            
            HtmlTableCell_exposer.def( 
                "onInit"
                , onInit_function_type( &HtmlTableCell_wrapper::default_onInit ) );
        
        }
        { //::osiris::IHtmlControl::onLoad
        
            typedef void ( HtmlTableCell_wrapper::*onLoad_function_type )(  ) ;
            
            HtmlTableCell_exposer.def( 
                "onLoad"
                , onLoad_function_type( &HtmlTableCell_wrapper::default_onLoad ) );
        
        }
        { //::osiris::IHtmlControl::onLoadViewState
        
            typedef void ( HtmlTableCell_wrapper::*onLoadViewState_function_type )( ::osiris::DataTree const & ) ;
            
            HtmlTableCell_exposer.def( 
                "onLoadViewState"
                , onLoadViewState_function_type( &HtmlTableCell_wrapper::default_onLoadViewState )
                , ( ::boost::python::arg("state") ) );
        
        }
        { //::osiris::IHtmlControl::onPreRender
        
            typedef void ( HtmlTableCell_wrapper::*onPreRender_function_type )(  ) ;
            
            HtmlTableCell_exposer.def( 
                "onPreRender"
                , onPreRender_function_type( &HtmlTableCell_wrapper::default_onPreRender ) );
        
        }
        { //::osiris::IHtmlControl::onSaveViewState
        
            typedef void ( HtmlTableCell_wrapper::*onSaveViewState_function_type )( ::osiris::DataTree & ) ;
            
            HtmlTableCell_exposer.def( 
                "onSaveViewState"
                , onSaveViewState_function_type( &HtmlTableCell_wrapper::default_onSaveViewState )
                , ( ::boost::python::arg("state") ) );
        
        }
        { //::osiris::IHtmlControl::renderAttributes
        
            typedef void ( ::osiris::IHtmlControl::*renderAttributes_function_type )( ::osiris::HtmlWriter & ) ;
            typedef void ( HtmlTableCell_wrapper::*default_renderAttributes_function_type )( ::osiris::HtmlWriter & ) ;
            
            HtmlTableCell_exposer.def( 
                "renderAttributes"
                , renderAttributes_function_type(&::osiris::IHtmlControl::renderAttributes)
                , default_renderAttributes_function_type(&HtmlTableCell_wrapper::default_renderAttributes)
                , ( ::boost::python::arg("writer") ) );
        
        }
        { //::osiris::IHtmlControl::renderChilds
        
            typedef void ( ::osiris::IHtmlControl::*renderChilds_function_type )( ::osiris::HtmlWriter & ) ;
            typedef void ( HtmlTableCell_wrapper::*default_renderChilds_function_type )( ::osiris::HtmlWriter & ) ;
            
            HtmlTableCell_exposer.def( 
                "renderChilds"
                , renderChilds_function_type(&::osiris::IHtmlControl::renderChilds)
                , default_renderChilds_function_type(&HtmlTableCell_wrapper::default_renderChilds)
                , ( ::boost::python::arg("writer") ) );
        
        }
        { //::osiris::IHtmlControl::saveViewState
        
            typedef void ( HtmlTableCell_wrapper::*saveViewState_function_type )( ::osiris::DataTree & ) ;
            
            HtmlTableCell_exposer.def( 
                "saveViewState"
                , saveViewState_function_type( &HtmlTableCell_wrapper::saveViewState )
                , ( ::boost::python::arg("states") ) );
        
        }
        { //property "colSpan"[fget=::osiris::HtmlTableCell::getColSpan, fset=::osiris::HtmlTableCell::setColSpan]
        
            typedef ::osiris::HtmlUnit ( ::osiris::HtmlTableCell::*fget )(  ) const;
            typedef void ( ::osiris::HtmlTableCell::*fset )( ::osiris::HtmlUnit const & ) ;
            
            HtmlTableCell_exposer.add_property( 
                "colSpan"
                , fget( &::osiris::HtmlTableCell::getColSpan )
                , fset( &::osiris::HtmlTableCell::setColSpan )
                , "get\\set property, built on top of \"osiris::HtmlUnit osiris::HtmlTableCell::getColSpan() const [member function]\" and \"void osiris::HtmlTableCell::setColSpan(osiris::HtmlUnit const & value) [member function]\"" );
        
        }
        { //property "rowSpan"[fget=::osiris::HtmlTableCell::getRowSpan, fset=::osiris::HtmlTableCell::setRowSpan]
        
            typedef ::osiris::HtmlUnit ( ::osiris::HtmlTableCell::*fget )(  ) const;
            typedef void ( ::osiris::HtmlTableCell::*fset )( ::osiris::HtmlUnit const & ) ;
            
            HtmlTableCell_exposer.add_property( 
                "rowSpan"
                , fget( &::osiris::HtmlTableCell::getRowSpan )
                , fset( &::osiris::HtmlTableCell::setRowSpan )
                , "get\\set property, built on top of \"osiris::HtmlUnit osiris::HtmlTableCell::getRowSpan() const [member function]\" and \"void osiris::HtmlTableCell::setRowSpan(osiris::HtmlUnit const & value) [member function]\"" );
        
        }
        ::boost::python::register_ptr_to_python< boost::shared_ptr< ::osiris::HtmlTableCell > >();
        ::boost::python::implicitly_convertible< boost::shared_ptr< ::osiris::HtmlTableCell >, boost::shared_ptr< ::boost::noncopyable_::noncopyable > >();
        ::boost::python::implicitly_convertible< boost::shared_ptr< ::osiris::HtmlTableCell >, boost::shared_ptr< ::boost::signals::trackable > >();
        ::boost::python::implicitly_convertible< boost::shared_ptr< ::osiris::HtmlTableCell >, boost::shared_ptr< ::osiris::enable_this_ptr< osiris::IHtmlControl > > >();
        ::boost::python::implicitly_convertible< boost::shared_ptr< ::osiris::HtmlTableCell >, boost::shared_ptr< ::osiris::Object > >();
        ::boost::python::implicitly_convertible< boost::shared_ptr< ::osiris::HtmlTableHeader >, boost::shared_ptr< ::osiris::HtmlTableCell > >();
    }

}
