// This file has been generated by Py++.

#ifndef HtmlEvents_hpp__pyplusplus_wrapper
#define HtmlEvents_hpp__pyplusplus_wrapper

void register_HtmlEvents_class();

#endif//HtmlEvents_hpp__pyplusplus_wrapper
