// This file has been generated by Py++.

#include "stdafx.h"
#include "pypluspluscommon.h"
#include "boost/python.hpp"
#include "__call_policies.pypp.hpp"
#include "htmlcheckbox.h"
#include "datatree.h"
#include "htmlattributes.h"
#include "htmlevent.h"
#include "eventssource.h"
#include "htmlvirtualpage.h"
#include "htmlwriter.h"
#include "httprequest.h"
#include "httpresponse.h"
#include "httpsession.h"
#include "htmlcheckbox.pypp.hpp"

namespace bp = boost::python;

struct HtmlCheckBox_wrapper : ::osiris::HtmlCheckBox, ::osiris::PythonWrapper< ::osiris::HtmlCheckBox > {

    HtmlCheckBox_wrapper( )
    : ::osiris::HtmlCheckBox( )
      , ::osiris::PythonWrapper< ::osiris::HtmlCheckBox >(){
        // null constructor
    
    }

    static boost::python::object getAutoPostBack( ::osiris::HtmlCheckBox const & inst ){
        ::osiris::PythonThreadSaver __pythreadSaver;
        bool result = inst.getAutoPostBack();
        __pythreadSaver.restore();
        return boost::python::object( result );
    }

    static boost::python::object getCheck( ::osiris::HtmlCheckBox const & inst ){
        ::osiris::PythonThreadSaver __pythreadSaver;
        bool result = inst.getCheck();
        __pythreadSaver.restore();
        return boost::python::object( result );
    }

    virtual void renderAttributes( ::osiris::HtmlWriter & writer ) {
        ::osiris::PythonState __pystate(getPythonThreadState());
        if( ::osiris::PythonOverride func_renderAttributes = this->get_override( "renderAttributes" ) )
            func_renderAttributes( boost::ref(writer) );
        else{
            __pystate.leave();
            this->::osiris::HtmlCheckBox::renderAttributes( boost::ref(writer) );
        }
    }
    
    void default_renderAttributes( ::osiris::HtmlWriter & writer ) {
        ::osiris::PythonThreadSaver __pythreadSaver;
        ::osiris::HtmlCheckBox::renderAttributes( boost::ref(writer) );
    }

    static void setAutoPostBack( ::osiris::HtmlCheckBox & inst, bool autoPostBack ){
        ::osiris::PythonThreadSaver __pythreadSaver;
        inst.setAutoPostBack(autoPostBack);
        __pythreadSaver.restore();
    }

    static void setCheck( ::osiris::HtmlCheckBox & inst, bool check ){
        ::osiris::PythonThreadSaver __pythreadSaver;
        inst.setCheck(check);
        __pythreadSaver.restore();
    }

    bool decodeEvent( ::osiris::String const & command, ::osiris::String & eventName, ::osiris::HtmlEvent & e ) const {
        return ::osiris::IHtmlControl::decodeEvent( boost::ref(command), boost::ref(eventName), boost::ref(e) );
    }

    ::osiris::String encodeEvent( ::osiris::String const & eventName, ::osiris::HtmlEvent const * e=(osiris::null) ) const {
        return ::osiris::IHtmlControl::encodeEvent( boost::ref(eventName), boost::python::ptr(e) );
    }

    virtual ::boost::shared_ptr< osiris::HttpSession > getSession(  ) const  {
        ::osiris::PythonState __pystate(getPythonThreadState());
        if( ::osiris::PythonOverride func_getSession = this->get_override( "getSession" ) )
            return func_getSession(  );
        else{
            __pystate.leave();
            return this->::osiris::IHtmlControl::getSession(  );
        }
    }
    
    ::boost::shared_ptr< osiris::HttpSession > default_getSession(  ) const  {
        ::osiris::PythonThreadSaver __pythreadSaver;
        return ::osiris::IHtmlControl::getSession( );
    }

    virtual void onEvent( ::osiris::String const & name, ::osiris::IEvent * e=(osiris::null) ){
        ::osiris::PythonState __pystate(getPythonThreadState());
        if( ::osiris::PythonOverride func_onEvent = this->get_override( "onEvent" ) )
            func_onEvent( boost::ref(name), boost::python::ptr(e) );
        else{
            __pystate.leave();
            this->::osiris::IHtmlControl::onEvent( boost::ref(name), boost::python::ptr(e) );
        }
    }
    
    virtual void default_onEvent( ::osiris::String const & name, ::osiris::IEvent * e=(osiris::null) ){
        ::osiris::PythonThreadSaver __pythreadSaver;
        ::osiris::IHtmlControl::onEvent( boost::ref(name), boost::python::ptr(e) );
    }

    virtual void onInit(  ){
        ::osiris::PythonState __pystate(getPythonThreadState());
        if( ::osiris::PythonOverride func_onInit = this->get_override( "onInit" ) )
            func_onInit(  );
        else{
            __pystate.leave();
            this->::osiris::IHtmlInput::onInit(  );
        }
    }
    
    virtual void default_onInit(  ){
        ::osiris::PythonThreadSaver __pythreadSaver;
        ::osiris::IHtmlInput::onInit( );
    }

    virtual void onLoad(  ){
        ::osiris::PythonState __pystate(getPythonThreadState());
        if( ::osiris::PythonOverride func_onLoad = this->get_override( "onLoad" ) )
            func_onLoad(  );
        else{
            __pystate.leave();
            this->::osiris::IHtmlControl::onLoad(  );
        }
    }
    
    virtual void default_onLoad(  ){
        ::osiris::PythonThreadSaver __pythreadSaver;
        ::osiris::IHtmlControl::onLoad( );
    }

    virtual void onLoadViewState( ::osiris::DataTree const & state ){
        ::osiris::PythonState __pystate(getPythonThreadState());
        if( ::osiris::PythonOverride func_onLoadViewState = this->get_override( "onLoadViewState" ) )
            func_onLoadViewState( boost::ref(state) );
        else{
            __pystate.leave();
            this->::osiris::IHtmlControl::onLoadViewState( boost::ref(state) );
        }
    }
    
    virtual void default_onLoadViewState( ::osiris::DataTree const & state ){
        ::osiris::PythonThreadSaver __pythreadSaver;
        ::osiris::IHtmlControl::onLoadViewState( boost::ref(state) );
    }

    virtual void onPreRender(  ){
        ::osiris::PythonState __pystate(getPythonThreadState());
        if( ::osiris::PythonOverride func_onPreRender = this->get_override( "onPreRender" ) )
            func_onPreRender(  );
        else{
            __pystate.leave();
            this->::osiris::IHtmlControl::onPreRender(  );
        }
    }
    
    virtual void default_onPreRender(  ){
        ::osiris::PythonThreadSaver __pythreadSaver;
        ::osiris::IHtmlControl::onPreRender( );
    }

    virtual void onRender( ::osiris::HtmlWriter & writer ){
        ::osiris::PythonState __pystate(getPythonThreadState());
        if( ::osiris::PythonOverride func_onRender = this->get_override( "onRender" ) )
            func_onRender( boost::ref(writer) );
        else{
            __pystate.leave();
            this->::osiris::IHtmlInput::onRender( boost::ref(writer) );
        }
    }
    
    virtual void default_onRender( ::osiris::HtmlWriter & writer ){
        ::osiris::PythonThreadSaver __pythreadSaver;
        ::osiris::IHtmlInput::onRender( boost::ref(writer) );
    }

    virtual void onSaveViewState( ::osiris::DataTree & state ){
        ::osiris::PythonState __pystate(getPythonThreadState());
        if( ::osiris::PythonOverride func_onSaveViewState = this->get_override( "onSaveViewState" ) )
            func_onSaveViewState( boost::ref(state) );
        else{
            __pystate.leave();
            this->::osiris::IHtmlControl::onSaveViewState( boost::ref(state) );
        }
    }
    
    virtual void default_onSaveViewState( ::osiris::DataTree & state ){
        ::osiris::PythonThreadSaver __pythreadSaver;
        ::osiris::IHtmlControl::onSaveViewState( boost::ref(state) );
    }

    virtual void renderChilds( ::osiris::HtmlWriter & writer ) {
        ::osiris::PythonState __pystate(getPythonThreadState());
        if( ::osiris::PythonOverride func_renderChilds = this->get_override( "renderChilds" ) )
            func_renderChilds( boost::ref(writer) );
        else{
            __pystate.leave();
            this->::osiris::IHtmlControl::renderChilds( boost::ref(writer) );
        }
    }
    
    void default_renderChilds( ::osiris::HtmlWriter & writer ) {
        ::osiris::PythonThreadSaver __pythreadSaver;
        ::osiris::IHtmlControl::renderChilds( boost::ref(writer) );
    }

    void saveViewState( ::osiris::DataTree & states ){
        ::osiris::IHtmlControl::saveViewState( boost::ref(states) );
    }

};

void register_HtmlCheckBox_class(){

    { //::osiris::HtmlCheckBox
        typedef ::boost::python::class_< HtmlCheckBox_wrapper, ::boost::python::bases< ::osiris::IHtmlInput >, ::boost::noncopyable > HtmlCheckBox_exposer_t;
        HtmlCheckBox_exposer_t HtmlCheckBox_exposer = HtmlCheckBox_exposer_t( "HtmlCheckBox", ::boost::python::init< >() );
        ::boost::python::scope HtmlCheckBox_scope( HtmlCheckBox_exposer );
        { //::osiris::HtmlCheckBox::getAutoPostBack
        
            typedef boost::python::object ( *getAutoPostBack_function_type )( ::osiris::HtmlCheckBox const & );
            
            HtmlCheckBox_exposer.def( 
                "getAutoPostBack"
                , getAutoPostBack_function_type( &HtmlCheckBox_wrapper::getAutoPostBack ) );
        
        }
        { //::osiris::HtmlCheckBox::getCheck
        
            typedef boost::python::object ( *getCheck_function_type )( ::osiris::HtmlCheckBox const & );
            
            HtmlCheckBox_exposer.def( 
                "getCheck"
                , getCheck_function_type( &HtmlCheckBox_wrapper::getCheck ) );
        
        }
        { //::osiris::HtmlCheckBox::renderAttributes
        
            typedef void ( ::osiris::HtmlCheckBox::*renderAttributes_function_type )( ::osiris::HtmlWriter & ) ;
            typedef void ( HtmlCheckBox_wrapper::*default_renderAttributes_function_type )( ::osiris::HtmlWriter & ) ;
            
            HtmlCheckBox_exposer.def( 
                "renderAttributes"
                , renderAttributes_function_type(&::osiris::HtmlCheckBox::renderAttributes)
                , default_renderAttributes_function_type(&HtmlCheckBox_wrapper::default_renderAttributes)
                , ( ::boost::python::arg("writer") ) );
        
        }
        { //::osiris::HtmlCheckBox::setAutoPostBack
        
            typedef void ( *setAutoPostBack_function_type )( ::osiris::HtmlCheckBox &,bool );
            
            HtmlCheckBox_exposer.def( 
                "setAutoPostBack"
                , setAutoPostBack_function_type( &HtmlCheckBox_wrapper::setAutoPostBack )
                , ( ::boost::python::arg("inst"), ::boost::python::arg("autoPostBack") ) );
        
        }
        { //::osiris::HtmlCheckBox::setCheck
        
            typedef void ( *setCheck_function_type )( ::osiris::HtmlCheckBox &,bool );
            
            HtmlCheckBox_exposer.def( 
                "setCheck"
                , setCheck_function_type( &HtmlCheckBox_wrapper::setCheck )
                , ( ::boost::python::arg("inst"), ::boost::python::arg("check") ) );
        
        }
        { //::osiris::IHtmlControl::decodeEvent
        
            typedef bool ( HtmlCheckBox_wrapper::*decodeEvent_function_type )( ::osiris::String const &,::osiris::String &,::osiris::HtmlEvent & ) const;
            
            HtmlCheckBox_exposer.def( 
                "decodeEvent"
                , decodeEvent_function_type( &HtmlCheckBox_wrapper::decodeEvent )
                , ( ::boost::python::arg("command"), ::boost::python::arg("eventName"), ::boost::python::arg("e") ) );
        
        }
        { //::osiris::IHtmlControl::encodeEvent
        
            typedef ::osiris::String ( HtmlCheckBox_wrapper::*encodeEvent_function_type )( ::osiris::String const &,::osiris::HtmlEvent const * ) const;
            
            HtmlCheckBox_exposer.def( 
                "encodeEvent"
                , encodeEvent_function_type( &HtmlCheckBox_wrapper::encodeEvent )
                , ( ::boost::python::arg("eventName"), ::boost::python::arg("e")=(osiris::null) ) );
        
        }
        { //::osiris::IHtmlControl::getSession
        
            typedef ::boost::shared_ptr< osiris::HttpSession > ( ::osiris::IHtmlControl::*getSession_function_type )(  ) const;
            typedef ::boost::shared_ptr< osiris::HttpSession > ( HtmlCheckBox_wrapper::*default_getSession_function_type )(  ) const;
            
            HtmlCheckBox_exposer.def( 
                "getSession"
                , getSession_function_type(&::osiris::IHtmlControl::getSession)
                , default_getSession_function_type(&HtmlCheckBox_wrapper::default_getSession) );
        
        }
        { //::osiris::IHtmlControl::onEvent
        
            typedef void ( HtmlCheckBox_wrapper::*onEvent_function_type )( ::osiris::String const &,::osiris::IEvent * ) ;
            
            HtmlCheckBox_exposer.def( 
                "onEvent"
                , onEvent_function_type( &HtmlCheckBox_wrapper::default_onEvent )
                , ( ::boost::python::arg("name"), ::boost::python::arg("e")=(osiris::null) ) );
        
        }
        { //::osiris::IHtmlInput::onInit
        
            typedef void ( HtmlCheckBox_wrapper::*onInit_function_type )(  ) ;
            
            HtmlCheckBox_exposer.def( 
                "onInit"
                , onInit_function_type( &HtmlCheckBox_wrapper::default_onInit ) );
        
        }
        { //::osiris::IHtmlControl::onLoad
        
            typedef void ( HtmlCheckBox_wrapper::*onLoad_function_type )(  ) ;
            
            HtmlCheckBox_exposer.def( 
                "onLoad"
                , onLoad_function_type( &HtmlCheckBox_wrapper::default_onLoad ) );
        
        }
        { //::osiris::IHtmlControl::onLoadViewState
        
            typedef void ( HtmlCheckBox_wrapper::*onLoadViewState_function_type )( ::osiris::DataTree const & ) ;
            
            HtmlCheckBox_exposer.def( 
                "onLoadViewState"
                , onLoadViewState_function_type( &HtmlCheckBox_wrapper::default_onLoadViewState )
                , ( ::boost::python::arg("state") ) );
        
        }
        { //::osiris::IHtmlControl::onPreRender
        
            typedef void ( HtmlCheckBox_wrapper::*onPreRender_function_type )(  ) ;
            
            HtmlCheckBox_exposer.def( 
                "onPreRender"
                , onPreRender_function_type( &HtmlCheckBox_wrapper::default_onPreRender ) );
        
        }
        { //::osiris::IHtmlInput::onRender
        
            typedef void ( HtmlCheckBox_wrapper::*onRender_function_type )( ::osiris::HtmlWriter & ) ;
            
            HtmlCheckBox_exposer.def( 
                "onRender"
                , onRender_function_type( &HtmlCheckBox_wrapper::default_onRender )
                , ( ::boost::python::arg("writer") ) );
        
        }
        { //::osiris::IHtmlControl::onSaveViewState
        
            typedef void ( HtmlCheckBox_wrapper::*onSaveViewState_function_type )( ::osiris::DataTree & ) ;
            
            HtmlCheckBox_exposer.def( 
                "onSaveViewState"
                , onSaveViewState_function_type( &HtmlCheckBox_wrapper::default_onSaveViewState )
                , ( ::boost::python::arg("state") ) );
        
        }
        { //::osiris::IHtmlControl::renderChilds
        
            typedef void ( ::osiris::IHtmlControl::*renderChilds_function_type )( ::osiris::HtmlWriter & ) ;
            typedef void ( HtmlCheckBox_wrapper::*default_renderChilds_function_type )( ::osiris::HtmlWriter & ) ;
            
            HtmlCheckBox_exposer.def( 
                "renderChilds"
                , renderChilds_function_type(&::osiris::IHtmlControl::renderChilds)
                , default_renderChilds_function_type(&HtmlCheckBox_wrapper::default_renderChilds)
                , ( ::boost::python::arg("writer") ) );
        
        }
        { //::osiris::IHtmlControl::saveViewState
        
            typedef void ( HtmlCheckBox_wrapper::*saveViewState_function_type )( ::osiris::DataTree & ) ;
            
            HtmlCheckBox_exposer.def( 
                "saveViewState"
                , saveViewState_function_type( &HtmlCheckBox_wrapper::saveViewState )
                , ( ::boost::python::arg("states") ) );
        
        }
        { //property "autoPostBack"[fget=::osiris::HtmlCheckBox::getAutoPostBack, fset=::osiris::HtmlCheckBox::setAutoPostBack]
        
            typedef bool ( ::osiris::HtmlCheckBox::*fget )(  ) const;
            typedef void ( ::osiris::HtmlCheckBox::*fset )( bool ) ;
            
            HtmlCheckBox_exposer.add_property( 
                "autoPostBack"
                , fget( &::osiris::HtmlCheckBox::getAutoPostBack )
                , fset( &::osiris::HtmlCheckBox::setAutoPostBack )
                , "get\\set property, built on top of \"bool osiris::HtmlCheckBox::getAutoPostBack() const [member function]\" and \"void osiris::HtmlCheckBox::setAutoPostBack(bool autoPostBack) [member function]\"" );
        
        }
        { //property "check"[fget=::osiris::HtmlCheckBox::getCheck, fset=::osiris::HtmlCheckBox::setCheck]
        
            typedef bool ( ::osiris::HtmlCheckBox::*fget )(  ) const;
            typedef void ( ::osiris::HtmlCheckBox::*fset )( bool ) ;
            
            HtmlCheckBox_exposer.add_property( 
                "check"
                , fget( &::osiris::HtmlCheckBox::getCheck )
                , fset( &::osiris::HtmlCheckBox::setCheck )
                , "get\\set property, built on top of \"bool osiris::HtmlCheckBox::getCheck() const [member function]\" and \"void osiris::HtmlCheckBox::setCheck(bool check) [member function]\"" );
        
        }
    }

}
