// This file has been generated by Py++.

#ifndef HtmlParser_hpp__pyplusplus_wrapper
#define HtmlParser_hpp__pyplusplus_wrapper

void register_HtmlParser_class();

#endif//HtmlParser_hpp__pyplusplus_wrapper
