// This file has been generated by Py++.

#ifndef HtmlLinkButton_hpp__pyplusplus_wrapper
#define HtmlLinkButton_hpp__pyplusplus_wrapper

void register_HtmlLinkButton_class();

#endif//HtmlLinkButton_hpp__pyplusplus_wrapper
