// This file has been generated by Py++.

#include "stdafx.h"
#include "pypluspluscommon.h"
#include "boost/python.hpp"
#include "ievent.h"
#include "htmlevent.h"
#include "ievent.pypp.hpp"

namespace bp = boost::python;

void register_IEvent_class(){

    ::boost::python::class_< ::osiris::IEvent >( "IEvent", ::boost::python::init< >() );

}
