// This file has been generated by Py++.

#ifndef IEventCallback_hpp__pyplusplus_wrapper
#define IEventCallback_hpp__pyplusplus_wrapper

void register_IEventCallback_class();

#endif//IEventCallback_hpp__pyplusplus_wrapper
