// This file has been generated by Py++.

#ifndef IHttpServer_hpp__pyplusplus_wrapper
#define IHttpServer_hpp__pyplusplus_wrapper

void register_IHttpServer_class();

#endif//IHttpServer_hpp__pyplusplus_wrapper
