// This file has been generated by Py++.

#ifndef IPortalDatabase_hpp__pyplusplus_wrapper
#define IPortalDatabase_hpp__pyplusplus_wrapper

void register_IPortalDatabase_class();

#endif//IPortalDatabase_hpp__pyplusplus_wrapper
