// This file has been generated by Py++.

#include "stdafx.h"
#include "pypluspluscommon.h"
#include "boost/python.hpp"
#include "__call_policies.pypp.hpp"
#include "isisendpoint.h"
#include "isisconnection.h"
#include "isisendpoint.pypp.hpp"

namespace bp = boost::python;

static boost::python::object getActiveConnection_5c215cc9e6902f5630b5352756c4c588( ::osiris::IsisEndpoint const & inst ){
    ::osiris::PythonThreadSaver __pythreadSaver;
    ::boost::shared_ptr<osiris::IsisConnection> result = inst.getActiveConnection();
    __pythreadSaver.restore();
    return boost::python::object( result );
}

static boost::python::object getName_3ac2e5037aae07c266b94fa2d31f36aa( ::osiris::IsisEndpoint const & inst ){
    ::osiris::PythonThreadSaver __pythreadSaver;
    ::osiris::String result = inst.getName();
    __pythreadSaver.restore();
    return boost::python::object( result );
}

static boost::python::object getUrl_7ac0472b92bea982ca4ab123b4482d98( ::osiris::IsisEndpoint const & inst ){
    ::osiris::PythonThreadSaver __pythreadSaver;
    ::osiris::HttpUrl result = inst.getUrl();
    __pythreadSaver.restore();
    return boost::python::object( result );
}

static boost::python::object getEnabled_ce68bb4512869331d5ae1a87b204f0b1( ::osiris::IsisEndpoint const & inst ){
    ::osiris::PythonThreadSaver __pythreadSaver;
    bool result = inst.getEnabled();
    __pythreadSaver.restore();
    return boost::python::object( result );
}

static boost::python::object getPassword_45d633e3916d8c969f507895db1fb54e( ::osiris::IsisEndpoint const & inst ){
    ::osiris::PythonThreadSaver __pythreadSaver;
    ::osiris::String result = inst.getPassword();
    __pythreadSaver.restore();
    return boost::python::object( result );
}

static boost::python::object getLastEvent_d07e0a5ba6985e74bd5b9ceb3075a1f1( ::osiris::IsisEndpoint const & inst ){
    ::osiris::PythonThreadSaver __pythreadSaver;
    ::osiris::String result = inst.getLastEvent();
    __pythreadSaver.restore();
    return boost::python::object( result );
}

static boost::python::object isValid_fddeaa97245366239197c6bc03176ef6( ::osiris::IsisEndpoint const & inst ){
    ::osiris::PythonThreadSaver __pythreadSaver;
    bool result = inst.isValid();
    __pythreadSaver.restore();
    return boost::python::object( result );
}

static boost::python::object getIsisOptions_400af9f3841307d7552da34674e998c6( ::osiris::IsisEndpoint const & inst ){
    ::osiris::PythonThreadSaver __pythreadSaver;
    ::osiris::XMLOptions const & result = inst.getIsisOptions();
    __pythreadSaver.restore();
    typedef bp::return_value_policy< bp::copy_const_reference > call_policies_t;
    return boost::python::object( pyplusplus::call_policies::make_object< call_policies_t, ::osiris::XMLOptions const & >( result ) );
}

static void close_5d516c25c853d496f943c590d819f396( ::osiris::IsisEndpoint & inst ){
    ::osiris::PythonThreadSaver __pythreadSaver;
    inst.close();
    __pythreadSaver.restore();
}

static boost::python::object canStart_a6507f1ce1b9cb3b1d940307f5252d86( ::osiris::IsisEndpoint & inst ){
    ::osiris::PythonThreadSaver __pythreadSaver;
    bool result = inst.canStart();
    __pythreadSaver.restore();
    return boost::python::object( result );
}

static boost::python::object matchUrl_49f5a47c6531fe64ec9cd6848475ab5c( ::osiris::IsisEndpoint & inst, ::osiris::HttpUrl const & url ){
    ::osiris::PythonThreadSaver __pythreadSaver;
    bool result = inst.matchUrl(url);
    __pythreadSaver.restore();
    return boost::python::object( result );
}

static void parseSystemInformation_8bbb276dd0313f83d4c465a3fa8555c9( ::osiris::IsisEndpoint & inst, ::boost::shared_ptr< osiris::XMLNode > root ){
    ::osiris::PythonThreadSaver __pythreadSaver;
    inst.parseSystemInformation(root);
    __pythreadSaver.restore();
}

static void setEnabled_e6fae3d82204015b4f7f6e6f018e0e34( ::osiris::IsisEndpoint & inst, bool enabled ){
    ::osiris::PythonThreadSaver __pythreadSaver;
    inst.setEnabled(enabled);
    __pythreadSaver.restore();
}

static void setLastEvent_a1055dd72306b14be76285482e1d48f7( ::osiris::IsisEndpoint & inst, ::osiris::String const & lastEvent ){
    ::osiris::PythonThreadSaver __pythreadSaver;
    inst.setLastEvent(lastEvent);
    __pythreadSaver.restore();
}

static void setName_7a9d3b36a1141fca4b41cece4309fe72( ::osiris::IsisEndpoint & inst, ::osiris::String const & name ){
    ::osiris::PythonThreadSaver __pythreadSaver;
    inst.setName(name);
    __pythreadSaver.restore();
}

static void setPassword_cc726213351b6d49b08c4aa93436fc64( ::osiris::IsisEndpoint & inst, ::osiris::String const & password ){
    ::osiris::PythonThreadSaver __pythreadSaver;
    inst.setPassword(password);
    __pythreadSaver.restore();
}

static void setUrl_4be48cbe77c055f26febb988868c68f3( ::osiris::IsisEndpoint & inst, ::osiris::HttpUrl const & url ){
    ::osiris::PythonThreadSaver __pythreadSaver;
    inst.setUrl(url);
    __pythreadSaver.restore();
}

static void update_a258c26965165ef581962c1e7ee374f8( ::osiris::IsisEndpoint & inst, ::boost::shared_ptr< osiris::ConnectionsManager > connectionsManager ){
    ::osiris::PythonThreadSaver __pythreadSaver;
    inst.update(connectionsManager);
    __pythreadSaver.restore();
}

void register_IsisEndpoint_class(){

    { //::osiris::IsisEndpoint
        typedef ::boost::python::class_< ::osiris::IsisEndpoint, ::boost::noncopyable > IsisEndpoint_exposer_t;
        IsisEndpoint_exposer_t IsisEndpoint_exposer = IsisEndpoint_exposer_t( "IsisEndpoint", ::boost::python::init< ::osiris::UniqueID const &, ::osiris::UniqueID const & >(( ::boost::python::arg("portalID"), ::boost::python::arg("povID") )) );
        ::boost::python::scope IsisEndpoint_scope( IsisEndpoint_exposer );
        { //::osiris::IsisEndpoint::getActiveConnection
        
            typedef boost::python::object ( *getActiveConnection_function_type )( ::osiris::IsisEndpoint const & );
            
            IsisEndpoint_exposer.def( 
                "getActiveConnection"
                , getActiveConnection_function_type( &getActiveConnection_5c215cc9e6902f5630b5352756c4c588 ) );
        
        }
        { //::osiris::IsisEndpoint::getName
        
            typedef boost::python::object ( *getName_function_type )( ::osiris::IsisEndpoint const & );
            
            IsisEndpoint_exposer.def( 
                "getName"
                , getName_function_type( &getName_3ac2e5037aae07c266b94fa2d31f36aa ) );
        
        }
        { //::osiris::IsisEndpoint::getUrl
        
            typedef boost::python::object ( *getUrl_function_type )( ::osiris::IsisEndpoint const & );
            
            IsisEndpoint_exposer.def( 
                "getUrl"
                , getUrl_function_type( &getUrl_7ac0472b92bea982ca4ab123b4482d98 ) );
        
        }
        { //::osiris::IsisEndpoint::getEnabled
        
            typedef boost::python::object ( *getEnabled_function_type )( ::osiris::IsisEndpoint const & );
            
            IsisEndpoint_exposer.def( 
                "getEnabled"
                , getEnabled_function_type( &getEnabled_ce68bb4512869331d5ae1a87b204f0b1 ) );
        
        }
        { //::osiris::IsisEndpoint::getPassword
        
            typedef boost::python::object ( *getPassword_function_type )( ::osiris::IsisEndpoint const & );
            
            IsisEndpoint_exposer.def( 
                "getPassword"
                , getPassword_function_type( &getPassword_45d633e3916d8c969f507895db1fb54e ) );
        
        }
        { //::osiris::IsisEndpoint::getLastEvent
        
            typedef boost::python::object ( *getLastEvent_function_type )( ::osiris::IsisEndpoint const & );
            
            IsisEndpoint_exposer.def( 
                "getLastEvent"
                , getLastEvent_function_type( &getLastEvent_d07e0a5ba6985e74bd5b9ceb3075a1f1 ) );
        
        }
        { //::osiris::IsisEndpoint::isValid
        
            typedef boost::python::object ( *isValid_function_type )( ::osiris::IsisEndpoint const & );
            
            IsisEndpoint_exposer.def( 
                "isValid"
                , isValid_function_type( &isValid_fddeaa97245366239197c6bc03176ef6 ) );
        
        }
        { //::osiris::IsisEndpoint::getIsisOptions
        
            typedef boost::python::object ( *getIsisOptions_function_type )( ::osiris::IsisEndpoint const & );
            
            IsisEndpoint_exposer.def( 
                "getIsisOptions"
                , getIsisOptions_function_type( &getIsisOptions_400af9f3841307d7552da34674e998c6 ) );
        
        }
        { //::osiris::IsisEndpoint::close
        
            typedef void ( *close_function_type )( ::osiris::IsisEndpoint & );
            
            IsisEndpoint_exposer.def( 
                "close"
                , close_function_type( &close_5d516c25c853d496f943c590d819f396 ) );
        
        }
        { //::osiris::IsisEndpoint::canStart
        
            typedef boost::python::object ( *canStart_function_type )( ::osiris::IsisEndpoint & );
            
            IsisEndpoint_exposer.def( 
                "canStart"
                , canStart_function_type( &canStart_a6507f1ce1b9cb3b1d940307f5252d86 ) );
        
        }
        { //::osiris::IsisEndpoint::matchUrl
        
            typedef boost::python::object ( *matchUrl_function_type )( ::osiris::IsisEndpoint &,::osiris::HttpUrl const & );
            
            IsisEndpoint_exposer.def( 
                "matchUrl"
                , matchUrl_function_type( &matchUrl_49f5a47c6531fe64ec9cd6848475ab5c )
                , ( ::boost::python::arg("inst"), ::boost::python::arg("url") ) );
        
        }
        { //::osiris::IsisEndpoint::parseSystemInformation
        
            typedef void ( *parseSystemInformation_function_type )( ::osiris::IsisEndpoint &,::boost::shared_ptr<osiris::XMLNode> );
            
            IsisEndpoint_exposer.def( 
                "parseSystemInformation"
                , parseSystemInformation_function_type( &parseSystemInformation_8bbb276dd0313f83d4c465a3fa8555c9 )
                , ( ::boost::python::arg("inst"), ::boost::python::arg("root") ) );
        
        }
        { //::osiris::IsisEndpoint::setEnabled
        
            typedef void ( *setEnabled_function_type )( ::osiris::IsisEndpoint &,bool );
            
            IsisEndpoint_exposer.def( 
                "setEnabled"
                , setEnabled_function_type( &setEnabled_e6fae3d82204015b4f7f6e6f018e0e34 )
                , ( ::boost::python::arg("inst"), ::boost::python::arg("enabled") ) );
        
        }
        { //::osiris::IsisEndpoint::setLastEvent
        
            typedef void ( *setLastEvent_function_type )( ::osiris::IsisEndpoint &,::osiris::String const & );
            
            IsisEndpoint_exposer.def( 
                "setLastEvent"
                , setLastEvent_function_type( &setLastEvent_a1055dd72306b14be76285482e1d48f7 )
                , ( ::boost::python::arg("inst"), ::boost::python::arg("lastEvent") ) );
        
        }
        { //::osiris::IsisEndpoint::setName
        
            typedef void ( *setName_function_type )( ::osiris::IsisEndpoint &,::osiris::String const & );
            
            IsisEndpoint_exposer.def( 
                "setName"
                , setName_function_type( &setName_7a9d3b36a1141fca4b41cece4309fe72 )
                , ( ::boost::python::arg("inst"), ::boost::python::arg("name") ) );
        
        }
        { //::osiris::IsisEndpoint::setPassword
        
            typedef void ( *setPassword_function_type )( ::osiris::IsisEndpoint &,::osiris::String const & );
            
            IsisEndpoint_exposer.def( 
                "setPassword"
                , setPassword_function_type( &setPassword_cc726213351b6d49b08c4aa93436fc64 )
                , ( ::boost::python::arg("inst"), ::boost::python::arg("password") ) );
        
        }
        { //::osiris::IsisEndpoint::setUrl
        
            typedef void ( *setUrl_function_type )( ::osiris::IsisEndpoint &,::osiris::HttpUrl const & );
            
            IsisEndpoint_exposer.def( 
                "setUrl"
                , setUrl_function_type( &setUrl_4be48cbe77c055f26febb988868c68f3 )
                , ( ::boost::python::arg("inst"), ::boost::python::arg("url") ) );
        
        }
        { //::osiris::IsisEndpoint::update
        
            typedef void ( *update_function_type )( ::osiris::IsisEndpoint &,::boost::shared_ptr<osiris::ConnectionsManager> );
            
            IsisEndpoint_exposer.def( 
                "update"
                , update_function_type( &update_a258c26965165ef581962c1e7ee374f8 )
                , ( ::boost::python::arg("inst"), ::boost::python::arg("connectionsManager") ) );
        
        }
        { //property "name"[fget=::osiris::IsisEndpoint::getName, fset=::osiris::IsisEndpoint::setName]
        
            typedef ::osiris::String ( ::osiris::IsisEndpoint::*fget )(  ) const;
            typedef void ( ::osiris::IsisEndpoint::*fset )( ::osiris::String const & ) ;
            
            IsisEndpoint_exposer.add_property( 
                "name"
                , fget( &::osiris::IsisEndpoint::getName )
                , fset( &::osiris::IsisEndpoint::setName )
                , "get\\set property, built on top of \"osiris::String osiris::IsisEndpoint::getName() const [member function]\" and \"void osiris::IsisEndpoint::setName(osiris::String const & name) [member function]\"" );
        
        }
        { //property "url"[fget=::osiris::IsisEndpoint::getUrl, fset=::osiris::IsisEndpoint::setUrl]
        
            typedef ::osiris::HttpUrl ( ::osiris::IsisEndpoint::*fget )(  ) const;
            typedef void ( ::osiris::IsisEndpoint::*fset )( ::osiris::HttpUrl const & ) ;
            
            IsisEndpoint_exposer.add_property( 
                "url"
                , fget( &::osiris::IsisEndpoint::getUrl )
                , fset( &::osiris::IsisEndpoint::setUrl )
                , "get\\set property, built on top of \"osiris::HttpUrl osiris::IsisEndpoint::getUrl() const [member function]\" and \"void osiris::IsisEndpoint::setUrl(osiris::HttpUrl const & url) [member function]\"" );
        
        }
        { //property "enabled"[fget=::osiris::IsisEndpoint::getEnabled, fset=::osiris::IsisEndpoint::setEnabled]
        
            typedef bool ( ::osiris::IsisEndpoint::*fget )(  ) const;
            typedef void ( ::osiris::IsisEndpoint::*fset )( bool ) ;
            
            IsisEndpoint_exposer.add_property( 
                "enabled"
                , fget( &::osiris::IsisEndpoint::getEnabled )
                , fset( &::osiris::IsisEndpoint::setEnabled )
                , "get\\set property, built on top of \"bool osiris::IsisEndpoint::getEnabled() const [member function]\" and \"void osiris::IsisEndpoint::setEnabled(bool enabled) [member function]\"" );
        
        }
        { //property "password"[fget=::osiris::IsisEndpoint::getPassword, fset=::osiris::IsisEndpoint::setPassword]
        
            typedef ::osiris::String ( ::osiris::IsisEndpoint::*fget )(  ) const;
            typedef void ( ::osiris::IsisEndpoint::*fset )( ::osiris::String const & ) ;
            
            IsisEndpoint_exposer.add_property( 
                "password"
                , fget( &::osiris::IsisEndpoint::getPassword )
                , fset( &::osiris::IsisEndpoint::setPassword )
                , "get\\set property, built on top of \"osiris::String osiris::IsisEndpoint::getPassword() const [member function]\" and \"void osiris::IsisEndpoint::setPassword(osiris::String const & password) [member function]\"" );
        
        }
        { //property "lastEvent"[fget=::osiris::IsisEndpoint::getLastEvent, fset=::osiris::IsisEndpoint::setLastEvent]
        
            typedef ::osiris::String ( ::osiris::IsisEndpoint::*fget )(  ) const;
            typedef void ( ::osiris::IsisEndpoint::*fset )( ::osiris::String const & ) ;
            
            IsisEndpoint_exposer.add_property( 
                "lastEvent"
                , fget( &::osiris::IsisEndpoint::getLastEvent )
                , fset( &::osiris::IsisEndpoint::setLastEvent )
                , "get\\set property, built on top of \"osiris::String osiris::IsisEndpoint::getLastEvent() const [member function]\" and \"void osiris::IsisEndpoint::setLastEvent(osiris::String const & lastEvent) [member function]\"" );
        
        }
        { //property "activeConnection"[fget=::osiris::IsisEndpoint::getActiveConnection]
        
            typedef ::boost::shared_ptr<osiris::IsisConnection> ( ::osiris::IsisEndpoint::*fget )(  ) const;
            
            IsisEndpoint_exposer.add_property( 
                "activeConnection"
                , fget( &::osiris::IsisEndpoint::getActiveConnection )
                , "get property, built on top of \"boost::shared_ptr<osiris::IsisConnection> osiris::IsisEndpoint::getActiveConnection() const [member function]\"" );
        
        }
        { //property "isisOptions"[fget=::osiris::IsisEndpoint::getIsisOptions]
        
            typedef ::osiris::XMLOptions const & ( ::osiris::IsisEndpoint::*fget )(  ) const;
            
            IsisEndpoint_exposer.add_property( 
                "isisOptions"
                , ::boost::python::make_function( 
                      fget( &::osiris::IsisEndpoint::getIsisOptions )
                    , bp::return_value_policy< bp::copy_const_reference >() ) 
                , "get property, built on top of \"osiris::XMLOptions const & osiris::IsisEndpoint::getIsisOptions() const [member function]\"" );
        
        }
        ::boost::python::register_ptr_to_python< boost::shared_ptr< ::osiris::IsisEndpoint > >();
        ::boost::python::implicitly_convertible< boost::shared_ptr< ::osiris::IsisEndpoint >, boost::shared_ptr< ::osiris::enable_this_ptr< osiris::IsisEndpoint > > >();
        ::boost::python::implicitly_convertible< boost::shared_ptr< ::osiris::IsisEndpoint >, boost::shared_ptr< ::osiris::Object > >();
    }

}
