// This file has been generated by Py++.

#ifndef IXMLResolver_hpp__pyplusplus_wrapper
#define IXMLResolver_hpp__pyplusplus_wrapper

void register_IXMLResolver_class();

#endif//IXMLResolver_hpp__pyplusplus_wrapper
