// This file has been generated by Py++.

#ifndef OMLHtmlWrapper_hpp__pyplusplus_wrapper
#define OMLHtmlWrapper_hpp__pyplusplus_wrapper

void register_OMLHtmlWrapper_class();

#endif//OMLHtmlWrapper_hpp__pyplusplus_wrapper
