// This file has been generated by Py++.

#include "stdafx.h"
#include "pypluspluscommon.h"
#include "boost/python.hpp"
#include "searchpolloptions.h"
#include "idesearchparam.h"
#include "searchpolloptions.pypp.hpp"

namespace bp = boost::python;

struct SearchPollOptions_wrapper : ::osiris::SearchPollOptions, ::osiris::PythonWrapper< ::osiris::SearchPollOptions > {

    SearchPollOptions_wrapper(::osiris::SearchPollOptions const & arg )
    : ::osiris::SearchPollOptions( arg )
      , ::osiris::PythonWrapper< ::osiris::SearchPollOptions >(){
        // copy constructor
        
    }

    SearchPollOptions_wrapper( )
    : ::osiris::SearchPollOptions( )
      , ::osiris::PythonWrapper< ::osiris::SearchPollOptions >(){
        // nullptr constructor
    
    }

    virtual ::boost::shared_ptr< osiris::IdeSearchParam > getControl(  ) {
        ::osiris::PythonState __pystate(getPythonThreadState());
        if( ::osiris::PythonOverride func_getControl = this->get_override( "getControl" ) )
            return func_getControl(  );
        else{
            __pystate.leave();
            return this->::osiris::ISearchOptions::getControl(  );
        }
    }
    
    ::boost::shared_ptr< osiris::IdeSearchParam > default_getControl(  ) {
        ::osiris::PythonThreadSaver __pythreadSaver;
        return ::osiris::ISearchOptions::getControl( );
    }

};

void register_SearchPollOptions_class(){

    ::boost::python::class_< SearchPollOptions_wrapper, ::boost::python::bases< ::osiris::ISearchOptions > >( "SearchPollOptions", ::boost::python::init< >() )    
        .def( 
            "getControl"
            , (::boost::shared_ptr< osiris::IdeSearchParam > ( ::osiris::ISearchOptions::* )(  ) )(&::osiris::ISearchOptions::getControl)
            , (::boost::shared_ptr< osiris::IdeSearchParam > ( SearchPollOptions_wrapper::* )(  ) )(&SearchPollOptions_wrapper::default_getControl) );

}
