// This file has been generated by Py++.

#ifndef SearchResultsDatabase_hpp__pyplusplus_wrapper
#define SearchResultsDatabase_hpp__pyplusplus_wrapper

void register_SearchResultsDatabase_class();

#endif//SearchResultsDatabase_hpp__pyplusplus_wrapper
