// This file has been generated by Py++.

#ifndef SearchModelOptions_hpp__pyplusplus_wrapper
#define SearchModelOptions_hpp__pyplusplus_wrapper

void register_SearchModelOptions_class();

#endif//SearchModelOptions_hpp__pyplusplus_wrapper
