// This file has been generated by Py++.

#ifndef StringVector_hpp__pyplusplus_wrapper
#define StringVector_hpp__pyplusplus_wrapper

void register_StringVector_class();

#endif//StringVector_hpp__pyplusplus_wrapper
