<?php
/**
* @package Isis
* @copyright Copyright (C) 2008 Osiris Team. All rights reserved.
* @license http://www.gnu.org/copyleft/lgpl.html GNU/LGPL, see LICENSE.php
* This program is free software; you can redistribute it and/or modify it under 
* the terms of the GNU Lesser General Public License as published by the Free Software
* Foundation; either version 2 of the License, or (at your option) any later
* version.

* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.

* You should have received a copy of the GNU Lesser General Public License along with
* this program; if not, write to the Free Software Foundation, Inc., 59 Temple
* Place - Suite 330, Boston, MA 02111-1307, USA, or go to
* http://www.gnu.org/copyleft/lesser.txt.
* 
* Generated by Anubis / Osiris Tools. Fri, 11 Nov 11 19:00:24 +0100
*/
if(!defined('_LANG_INVITELINK_ISIS_INFO')) define('_LANG_INVITELINK_ISIS_INFO','Cliquez sur le lien suivant pour souscrire votre Osiris dans cet Isis.
<br /><br /><b>Vous devez avoir Osiris d\'installé, et déjà être enregistré sur le portail.</b>!
<br />Si vous n\'avez pas encore installé Osiris, vous pouvez le récupérer sur <a href="http://www.osiris-sps.org">le site officiel.</a>');
if(!defined('_LANG_INVITELINK_PORTAL_INFO')) define('_LANG_INVITELINK_PORTAL_INFO','Cliquez sur le lien suivant pour vous inscrire au portail.
<br /><br /><b>Vous devez avoir Osiris d\'installé pour rejoindre le portail</b>!
<br />Si vous n\'avez pas encore installé Osiris, vous pouvez le récupérer sur <a href="http://www.osiris-sps.org">le site officiel.</a>');
if(!defined('_LANG_INVITELINK_SUBMIT')) define('_LANG_INVITELINK_SUBMIT','Envoie');
if(!defined('_LANG_INVITELINK_SUGGEST')) define('_LANG_INVITELINK_SUGGEST','Le lien suivant peut être utilisé pour voir le lien d\'invitation:');
if(!defined('_LANG_INVITELINK_WIZARD')) define('_LANG_INVITELINK_WIZARD','Insérez votre lien d\'invitation ici <b>osiris://</b> pour avoir un lien d\'invitation <b>http://</b>');
if(!defined('_LANG_NOTALLOWEDURL')) define('_LANG_NOTALLOWEDURL','Vous n\'avez pas entré une url valide, ce n\'est pas un lien d\'invitation Osiris');
?>